title: Lerntagebuch Bibliotheks- und Archivinformatik
author: Nicole
email: nicole.meyer@stud.fhgr.ch
description: > # this means to ignore newlines
  Lerntagebuch für den Kurs Bibliotheks- und Archivinformatik HS2021 von Nicole

# social links
github_username:  Kekskaempferin # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

remote_theme: pages-themes/merlot@v0.2.0
plugins:- jekyll-remote-theme

gem "github-pages", group: :jekyll_plugins
